### ISSUE TITLE
"Next stop" not updating

### ISSUE THREAD

**Issue by sinsa92** [AdriDevelopsThings/iceportal_rich_presence#2]
I was riding the ICE 373 today from Basel to Bern, and somewhere around Liestal, I got this error:
![grafik](https://user-images.githubusercontent.com/36137659/210270906-7fec94fa-a135-4ea0-8542-755638360f9f.png)
The "next stop" in the rich presence also didn't update after that. (I never noticed it update, besides the timestamp)

After this, I tried to restart the application. However, the application told me to check whether I was connected with the ICE Wifi or not. I was connected, though (I tested it by reloading the site https://iceportal.de):
![grafik](https://user-images.githubusercontent.com/36137659/210271298-419b2211-83fa-4458-a433-6945c5a0cdb3.png)
![grafik](https://user-images.githubusercontent.com/36137659/210271382-58c63c5e-12fb-4a3d-b597-978fb476b3b4.png)

OS: Windows 10 Pro (Build 19045.2364)
ICE: 373 Basel-Bern (Complete train journey: Berlin-Interlaken)
Date: 02.01.2023

**Comment by AdriDevelopsThings** [comment]
Thanks for creating this issue. I fixed the issue in version 1.0.3
